bf16: true
cutoff_len: 2048
dataset: mire_train
dataset_dir: data
ddp_timeout: 180000000
do_train: true
finetuning_type: lora
flash_attn: fa2
gradient_accumulation_steps: 4
learning_rate: 5.0e-06
logging_steps: 5
lora_alpha: 16
lora_dropout: 0
lora_rank: 128
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 10000
model_name_or_path: Qwen/Qwen2-VL-2B-Instruct
model_revision: master
num_train_epochs: 3.0
optim: adamw_torch
output_dir: saves/Qwen2-VL-2B-Instruct/lora/train_2024-12-10-11-17-18
packing: false
per_device_train_batch_size: 2
pissa_convert: true
pissa_init: true
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 10
stage: sft
template: qwen2_vl
warmup_steps: 10
